### ISSUE TITLE
Bug in error message from snapshot listener

### ISSUE THREAD

**Issue by shiva-6** [googleapis/java-firestore#1085]
Query Listeners in the combination of whereGreaterThan and whereNotEqualTo filters is throwing an exception as expected but with a small bug in the error message where it says **com.google.cloud.firestore.FirestoreException: Backend ended Listen stream: Cannot have inequality filters on multiple properties: name** with only mentioning one field property whereas with other combinations the message was correct mentioning exactly what all the multiple properties were.

**Comment by milaGGL** [comment]
Hi @shiva-6  , thank you so much for reporting this issue. I will look into this and keep you updated.

**Comment by milaGGL** [comment]
> Query Listeners in the combination of whereGreaterThan and whereNotEqualTo filters is throwing an exception..
... whereas with other combinations the message was correct mentioning exactly what all the multiple properties were.

hi @shiva-6 , I was able to reproduce the issue on snapshot listener. It is only listing the second inequality property as you mentioned, but this issue is not limited to the "whereGreaterThan" and "whereNotEqualTo" combo. https://github.com/googleapis/java-firestore/pull/1093/files

While we look into this, could you please help try other combination and double check the error messages? It would be super appreciated if you could provide us with your reproducible code and/or screenshot of the error messages with different inequality combinations.

**Comment by partapu** [comment]
Another Query Listeners combination with an improper error message

db.collection("restaurants_p/6gaKC7syRE1qUGOD0cZZ/reviews").whereGreaterThan("rating",4.4).whereLessThan("author","ramesh");

Error message: Backend ended Listen stream: Cannot have inequality filters on multiple properties: author

**Comment by milaGGL** [comment]
Hi @partapu, thank you for sharing this. Seems like this is not only limited to specific combinations.

**Comment by milaGGL** [comment]
Hi @shiva-6 , thank you for filing this issue. The fix is added and it will be rolled out in the backend, but we don't have an ETA.  Googlers can see the changes in cl/490100051. 
I will close the github issue now, and will check again when the changes are released.
