### ISSUE TITLE
Set as part of Supported Data Type

### ISSUE THREAD

**Issue by irvifa** [googleapis/java-firestore#189]
**Is your feature request related to a problem? Please describe.**
Since sometimes we need to make sure the content of our data unique and implement is as a Set, however this is not supported yet in https://firebase.google.com/docs/firestore/manage-data/data-types.

**Describe the solution you'd like**
We might want to implement this in the future because converting Set to ArrayList before storing the object seems to be not that efficient.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by irvifa** [comment]
I notice that `MapValue` and `ArrayValue` in Firestore is using `protocolbuffer` in the implementation and then I saw this issue about set implementation in `protobuf` https://github.com/protocolbuffers/protobuf/issues/3359. Will this means that Set won't be considered as part of Firestore API?

**Comment by BenWhitehead** [comment]
Given that protobuf does not plan to support a Set type, it is unlikely this will be supported in Firestore. As far as having the conversion happen in the library rather than application code, I don't think it's a good idea given the potential gotchas in the conversion and the expectations that may arise regarding what the order becomes. It is safer for the application to take care of the conversion.
