### ISSUE TITLE
Remove dependency on jackson2

### ISSUE THREAD

**Issue by elharo** [googleapis/java-firestore#506]
Per go/json-madness

**Comment by huw0** [comment]
I would like to understand the rationale behind this?
Spring Boot uses Jackson by default and so it is helpful to also have Jackson used within Firestore.

**Comment by elharo** [comment]
See go/json-madness

**Comment by abhijeetshuklaoist** [comment]
Is this available for me to work on? If yes, please assign it me, I would like to work on it.

**Comment by abhijeetshuklaoist** [comment]
@elharo I have replaced Jackson with Gson but that does not sound a good thing because Gson considers Map (and Lists etc) as primitive types and converts them to corresponding types but looking at the MapperTest.primitiveDeserializeWrongTypeMap, that is not expected behaviour. 
Is my understanding correct?
Thanks!

**Comment by elharo** [comment]
I'd have to see the PR. It could be you need additional code to reproduce the current behavior. I don't know.

**Comment by knyttl** [comment]
> @elharo I have replaced Jackson with Gson but that does not sound

I think moving to Gson is a step backwards. Jackson is the current standard.

**Comment by elharo** [comment]
also see https://engdoc.corp.google.com/eng/doc/devguide/java/primer/index.md?cl=head#data-interchange-formats-serialization

Security team wants us to avoid jackson.
