### ISSUE TITLE
Replacing Timestamp with Java8 Instant or ability to use custom serializer

### ISSUE THREAD

**Issue by vojkny** [googleapis/java-firestore#509]
This is a follow up for an issue which was closed without any explanation:
https://github.com/googleapis/java-firestore/issues/88

**Is your feature request related to a problem? Please describe.**
We would like to use custom deserializer for using Java8 `Instant` or similar instead of proprietary `Timestamp`.

**Describe the solution you'd like**
The easiest would be registration of custom serializer like `Jackson` provides:

```
val objectMapper = ObjectMapper()
    .registerModule(JavaTimeModule())
```

**Additional context**
See the previously closed issue.

Note to Googlers (added by @dconeybe): This feature request is being tracked internally by b/326255898

**Comment by kolea2** [comment]
Hi @knyttl, thanks for raising this. I've labeled this as a feature request for a possible improvement.

**Comment by knyttl** [comment]
For anyone interested, I forked the repo and replaced the `com.google.cloud.Timestamp` implementation with java8's `java.time.Instant` one:

https://github.com/knyttl/java-firestore/commits/instant

This can be linked via [JitPack](https://jitpack.io/#knyttl/java-firestore/instant-SNAPSHOT) repository:

`implementation com.github.knyttl.java-firestore:google-cloud-firestore:instant-SNAPSHOT`

**Comment by PierrickPuimeanChieze** [comment]
I rise this issue again, custom serializer/converter would be awesome.

**Comment by dconeybe** [comment]
Thank you for this feature request. The old issue, https://github.com/googleapis/java-firestore/issues/88, was closed because Java 8 was not supported; however, starting in version 3.0.0 (https://github.com/googleapis/java-firestore/blob/main/CHANGELOG.md#300-2021-08-09) Java 7 support was dropped and Java 8 types can be used.

So there is no technical blocker for implementing a feature like this.

Unfortunately, however, the team does not have bandwidth in the foreseeable future to invest time in this feature. We have added it to our backlog and will keep this issue open and update it when we have an update.

**Comment by eranl** [comment]
I suggest *adding* support for `java.time.Instant` in addition to `com.google.cloud.Timestamp`, rather than replacing it, and doing so only in POJOs.

Currently, `com.google.cloud.Timestamp `and `java.util.Date` are supported as time types. The former is proprietary, which makes it hard to reuse POJOs outside of firestore, which would be very useful. The latter is outdated and limited in resolution.

I have a proposed implementation. Should I submit a PR?

**Comment by jonathan-santos-aerlingus** [comment]
Any update on this?

**Comment by dconeybe** [comment]
Unfortunatley, no update at this time.

**Comment by dconeybe** [comment]
A pull request wouldn't hurt, but I cannot guarantee that it would get the fix prioritized any sooner. A breaking change that _replaces_ `Timestamp` with `Instant` probably will be rejected because it is a breaking change, and a really bad one that cannot always be detected at compile time. Instead, a solution will likely need to _add_ support for `Instant` while maintaining backwards compatibility with `Timestamp`. You'd also need to be willing to engage in some back-and-forth as we request stylistic changes and unit test coverage. It's up to you what you want to do.

**Comment by eranl** [comment]
There you go, @dconeybe

**Comment by dconeybe** [comment]
@eranl My coworker, @tom-andersen, will work with you on getting your PR merged. Thanks for the effort you put into it!

**Comment by tom-andersen** [comment]
@eranl Thanks! Your PR hit the spot.

**Comment by eranl** [comment]
Thanks, @tom-andersen.
Is there some kind of sync process with the [android library](https://github.com/firebase/firebase-android-sdk), or should I submit a similar PR there?

**Comment by tom-andersen** [comment]
@eranl No, Android is developed independently. Feel free to tag me on Android PR, and I will be sure to see it through to merge.

**Comment by dconeybe** [comment]
Just be careful with android because firebase-android-sdk supports older versions of Android that do not have `java.time.Instant`. So you'll need to do things like check `Build.VERSION.SDK_INT >= Build.VERSION_CODES.XXX` before referencing the `Instant` class.
