### ISSUE TITLE
New methods to get Array and Map fields without unchecked casts 

### ISSUE THREAD

**Issue by lpellegr** [googleapis/java-firestore#60]
**Is your feature request related to a problem? Please describe.**

The _DocumentSnapshot_ class provides methods to retrieve a field by Firestore type, with the exception of 2 types: Array and Map. Retrieving the content of an Array or Map field and assigning it to a variable requires to call `get` and to do an unchecked cast. 

**Describe the solution you'd like**

For instance, adding 2 new methods such as `public <T> List<T> getArray(@Nonnull String field)` and `public <T> Map<String, T> getMap(@Nonnull String field)`.

**Describe alternatives you've considered**

Making an unchecked cast or using get with the second parameter that accepts a value type class but still requires an unchecked cast.

**Additional context**
I guess there is maybe a reason for not providing such methods (i.e. values for Array and Map are heterogeneous in Firestore and you do not want unchecked cast in your client library?). In that case, a note in the documentation suggesting the recommended approach would be helpful.

**Comment by lpellegr** [comment]
Here is a basic utility class I have written to prevent boilerplate code and unchecked casts at several places in different projects:

```java
public final class Firestore {

    private Firestore() {
    }

    public static <T> List<T> getArray(DocumentSnapshot documentSnapshot, FieldPath fieldPath) {
        return getArray(documentSnapshot, fieldPath.toString());
    }

    @Nullable
    @SuppressWarnings("unchecked")
    public static <T> List<T> getArray(DocumentSnapshot documentSnapshot, String fieldPath) {
        Object fieldValue = documentSnapshot.get(fieldPath);

        if (fieldValue == null) {
            return ImmutableList.of();
        }

        if (!(fieldValue instanceof List)) {
            throw new IllegalArgumentException("The field value at " + fieldPath + " is not an array");
        }

        return (List<T>) fieldValue;
    }

    public static <T> Map<String, T> getMap(DocumentSnapshot documentSnapshot, FieldPath fieldPath) {
        return getMap(documentSnapshot, fieldPath.toString());
    }

    @Nullable
    @SuppressWarnings("unchecked")
    public static <T> Map<String, T> getMap(DocumentSnapshot documentSnapshot, String fieldPath) {
        Object fieldValue = documentSnapshot.get(fieldPath);

        if (fieldValue == null) {
            return ImmutableMap.of();
        }

        if (!(fieldValue instanceof Map)) {
            throw new IllegalArgumentException("The field value at " + fieldPath + " is not a map");
        }

        return (Map<String, T>) fieldValue;
    }

}

```

I am wondering if this could be natively supported by this client library?

**Comment by BenWhitehead** [comment]
Good idea, it's something we can look into!

**Comment by BenWhitehead** [comment]
@lpellegr I've spoken with several folks from the Java OpenSource team here at Google and the consensus we've reached about this issue is: for now we don't want to add a method to the library following the code you have shared.

The reason for this are due to a few reasons:
1. Due to the nature of arrays in Firestore allowing storage of heterogeneous values, there is no easy way for us to create a method that can safely return `List<T>` for all scenarios. (We acknowledge that this is not an issue for those Firestore Arrays which do only contain homogeneous values, but there isn't currently a way for us to assert this in a safe and performant way for all users)
2. Due to the nature of Maps in Firestore also allowing storage of heterogeneous values, there is no easy way for us to create a method that can safely return `Map<String, T>` for all scenarios.
3. Given 1 and 2 we do not want to create a method on DocumentSnapshot that can shadow the possibility of a `ClassCastException` happening for some users. (We acknowledge that this is not an issue where homogeneous values are used, but again we can't guarantee that for all cases)
4. Given the unsafe nature of casting a full list, we feel it best to allow the compiler to show the warning to users and allow them to choose if they want to suppress it for a method/class or to make a wrapper method as you have done.
5. The nature of Java's implementation of Generics also leads to difficulty in us trying to provide a safe method to satisfy the heterogeneity of the underlying values
6. We may be able to look into creating some custom List-like & Map-like data structures that would be able to provide the necessary safety guarantees we would be comfortable with, but I do not know what the timeline for something like that would be.

For now I am going to close this issues, as I don't know when we'll be able to get to the extra work mentioned in 6.
